### ISSUE TITLE
CfgFunctions entfernen

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/grad-factions#1]
Nur eine pro Mission erlaubt --> kann grad-factions nicht einbinden.

https://github.com/gruppe-adler/grad-factions/blob/master/loadouts.hpp#L15

**Comment by Fusselwurm** [comment]
ooooh verdammich. CfgFunctions kann man nicht überschreiben? geht doch bei den andern klassen auch :sob:

**Comment by Fusselwurm** [comment]
fixed in ecac715719868d03abbecb3432bf4c1f13a21c85 @McDiod
