### ISSUE TITLE
Funkgeräte

### ISSUE THREAD

**Issue by SlantX** [gruppe-adler/grad-factions#11]
Es wurde berichtet, dass Leute in den Fireteams noch die kleinen "Quetschen" als Funkgeräte haben. Loadout war OCP/UCP und ich habe dort nur Heli-Piloten manuell hinzugefügt.

Erwartet habe ich, dass alle die 152er Funke haben, mit der wir üblicherweise spielen.

**Comment by McDiod** [comment]
Muss an grad-loadout oder unseren TFAR Einstellungen liegen.

**Comment by Fusselwurm** [comment]
existiert das Problem noch? Oder können TFAR- und grad-loadout - Verantwortliche das guten Gewissens  ignorieren?

**Comment by McDiod** [comment]
Existiert noch denk ich. Ich hab keine harten Fakten, aber ab und zu gibts immer Leute, die mit der Riflemanfunke starten, obwohl wir die eigentlich nirgends verbauen.

**Comment by SlantX** [comment]
Wird die standardmässig von TFAR vergeben, z.B. wenn GRAD Loadout an der Stelle nichts vergibt?

**Comment by Fusselwurm** [comment]
kommt drauf an ob du resetLoadout verwendest… uh… siehe https://github.com/gruppe-adler/grad-loadout/issues/21 :sweat:
