### ISSUE TITLE
Sinnvolle Einbindung von LMG / MMG und HMG samt Assistenten

### ISSUE THREAD

**Issue by Synch2k** [gruppe-adler/grad-factions#20]
Wie in Discord besprochen:

**Vanilla Paarungen**
LMG> soldier_AR_F & soldier_AAR_F
MMG> HeavyGunner_F 
HMG> support_MG_F & support_AMG_F 

**grad-loadout / factions Paarungen derzeit**
LMG> soldier_AR_F & soldier_AAR_F 
MMG> HeavyGunner_F & support_AMG_F

**Zukünftige Paarung**
LMG> soldier_AR_F & soldier_AAR_F
MMG> HeavyGunner_F & Soldier_A_F
HMG> support_MG_F & support_AMG_F

**Comment by McDiod** [comment]
PR merged
